require("hm.plugin_config.treesitter")
require("hm.plugin_config.vifm")
require("hm.plugin_config.indent_blankline")
require("hm.plugin_config.nvim_tree")
require("hm.plugin_config.lsp_config")
require("hm.plugin_config.telescope")
