#!/bin/bash
# The script allows to use google-chrome from dmenu or cli; usage: g - open site or use google search; g -y - search with yandex; g -w - search in wikipedia.

if [[ "$@" == *[а-яА-Я]* ]]
    then
    LanGu="ru"
else
    LanGu="en"
fi

while getopts y:w flag
    do
        case "${flag}" in
            y) SearchEngine="https://yandex.ru/search/?text=";;
            w) SearchEngine="https://${LanGu}.wikipedia.org/wiki/Special:Search?search=";;
        esac
    done

AllArgs=$@

if [ -z "$SearchEngine" ] && [[ "$@" != *.* ]]
    then
    SearchEngine="https://www.google.com/search?q="
elif (( $# >= 2 ))
then
    shift
    AllArgs=$@
fi

Sargs=$SearchEngine$AllArgs

google-chrome-stable --kiosk --new-window "$Sargs"
